# https://docs.github.com/en/actions
name: "Build"

# https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
  push:
    branches:
      - "**"
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # Every Sunday at 00:00
    - cron: "0 0 * * 0"
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker-image:
    name: "Docker Image"

    permissions:
      contents: "read"
      packages: "write"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - image: "golang:1.22-bookworm"
            tag: "go-1.22"

          - image: "php:8.1-fpm-bullseye"
            tag: "php-8.1"

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"

      - name: "Log in to the Container registry"
        uses: "docker/login-action@v3.4.0"
        if: github.ref == 'refs/heads/main'
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Extract metadata (tags, labels) for Docker"
        id: meta
        uses: "docker/metadata-action@v5.7.0"
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: "Build Docker image"
        uses: "docker/build-push-action@v6.15.0"
        with:
          build-args: |
            FROM_IMAGE=${{ matrix.image }}
          context: "."
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.tag }}"
